//! Row + DTO types shared between the storage API and its callers.

use serde::{Deserialize, Serialize};

/// New agent record (insert payload for [`crate::Store::record_agent_spawn`]).
///
/// `workspace_id` / `spell_run_id` are nullable in schema (SQLite ALTER ADD
/// COLUMN limitation) but should always be populated by spawn callers after
/// the workspace-as-first-class refactor — Step 3 of the rollout makes the
/// REST input mandatory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewAgent {
    pub id: String,
    pub cli: String,
    pub role: String,
    pub workspace: String,
    /// Unix-ms timestamp of the spawn event.
    pub spawned_at: i64,
    #[serde(default)]
    pub workspace_id: Option<String>,
    #[serde(default)]
    pub spell_run_id: Option<String>,
    /// Thread (direction) this agent belongs to. `None` = the workspace's
    /// main thread (legacy rows + pre-thread spawns land here).
    #[serde(default)]
    pub thread_id: Option<String>,
}

/// Full agent row as stored in `agents`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentRecord {
    pub id: String,
    pub cli: String,
    pub role: String,
    pub workspace: String,
    pub spawned_at: i64,
    pub killed_at: Option<i64>,
    pub shim_ready_at: Option<i64>,
    pub shim_exit_at: Option<i64>,
    pub shim_exit_code: Option<i32>,
    #[serde(default)]
    pub workspace_id: Option<String>,
    #[serde(default)]
    pub spell_run_id: Option<String>,
    #[serde(default)]
    pub thread_id: Option<String>,
    /// Unix-ms of the agent's most recent tool-level activity, persisted by the
    /// transcript tailer (migration 0013). `None` for agents that never emitted
    /// a tool event. The UI uses it to tell "wedged" from "idle" after a reload.
    #[serde(default)]
    pub last_activity_at: Option<i64>,
}

/// A "direction" inside a workspace — its own orchestrator + worker subtree +
/// dual ledger + (optionally) an isolated git worktree. See migration 0009.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreadRecord {
    pub id: String,
    pub workspace_id: String,
    pub slug: String,
    pub name: Option<String>,
    /// "shared" | "worktree"
    pub isolation: String,
    pub branch: Option<String>,
    pub cwd: String,
    /// "ready" | "preparing" | "failed"
    pub state: String,
    /// Per-direction model override (abstract tier opus|sonnet|haiku or a
    /// concrete model id). NULL = use the global default. Resolved per-CLI at
    /// spawn time. See migration 0014.
    #[serde(default)]
    pub model_tier: Option<String>,
    /// Per-direction reasoning/thinking effort (abstract low|medium|high|max).
    /// NULL = the model's own default. Mapped to each CLI's concrete value at
    /// spawn (effort_levels in the plugin manifest). See migration 0015.
    #[serde(default)]
    pub reasoning_effort: Option<String>,
    pub created_at: i64,
    #[serde(default)]
    pub deleted_at: Option<i64>,
}

/// Insert payload for [`crate::Store::create_thread`]. `id` + `slug` may be
/// generated by the store when left to the caller; here the caller supplies a
/// slug (e.g. "main" or "t-<rand>") since slug is meaningful (URL + bb prefix).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewThread {
    pub workspace_id: String,
    pub slug: String,
    #[serde(default)]
    pub name: Option<String>,
    pub isolation: String,
    #[serde(default)]
    pub branch: Option<String>,
    pub cwd: String,
    pub state: String,
}

/// New workspace record (insert payload for
/// [`crate::Store::create_workspace`]). `id` and `slug` are generated by the
/// store; callers only provide the user-facing fields.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewWorkspace {
    pub name: String,
    pub cwd: String,
    #[serde(default)]
    pub accent: Option<String>,
}

/// Full workspaces row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkspaceRecord {
    pub id: String,
    pub slug: String,
    pub name: String,
    pub cwd: String,
    #[serde(default)]
    pub accent: Option<String>,
    pub created_at: i64,
    #[serde(default)]
    pub deleted_at: Option<i64>,
}

/// Insert payload for an attached workspace root (a node in the workspace's
/// user-defined logical tree). `parent_id` points at another workspace_roots
/// row (or `None`); the tree is logical, not physical (see migration 0007).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewWorkspaceRoot {
    pub workspace_id: String,
    pub path: String,
    pub role: String,
    pub label: Option<String>,
    #[serde(default)]
    pub parent_id: Option<String>,
}

/// Full workspace_roots row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkspaceRootRecord {
    pub id: String,
    pub workspace_id: String,
    pub path: String,
    pub role: String,
    pub label: Option<String>,
    #[serde(default)]
    pub parent_id: Option<String>,
    pub created_at: i64,
}

/// New spell-run lineage record (insert payload for
/// [`crate::Store::create_spell_run`]).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewSpellRun {
    pub workspace_id: String,
    pub spell_name: String,
    pub task: String,
    #[serde(default)]
    pub caller_agent_id: Option<String>,
    pub started_at: i64,
}

/// New ad-hoc worker (insert payload for [`crate::Store::record_worker`]).
/// Magentic-One 重构后业务 agent 不再来自 spell+role,而是 orchestrator 在
/// runtime 用自定义 prompt 拉的临时工。这张表把"谁拉的、什么活、等啥信号"
/// 记下来,DAG / wake-coordinator / 回放都靠它。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewWorker {
    /// PTY agent_id(同时是 agents 表主键)。
    pub agent_id: String,
    /// 拉起这个 worker 的 orchestrator(或上一级 worker)的 agent_id。
    pub parent_agent_id: String,
    /// 仅 UI 显示用的 role 名字,例如 "writer" / "ui-coder" / "test-runner"。
    pub role_label: String,
    /// 注入给 worker 的完整 system prompt,留档便于回放。
    pub system_prompt: String,
    /// 完成后该写的黑板 key;无 handoff 留空字符串。P0-A 起由服务端 mint
    /// (`<workspace_id>/<thread_slug>/<role>.<kind>`),不再是 LLM 自选串。
    pub handoff_signal: String,
    /// JSON 序列化的 string array,等待的黑板 key。空数组 = 无依赖。P0-A 起
    /// 由 `consumes_json` 解析成的 minted keys 填入。
    pub depends_on_json: String,
    pub spawned_at: i64,

    // ── P0 (F1 角色/任务感知配给) ──────────────────────────────────────
    /// 校验过的角色注册表 slug(P0-B)。`role_label` 保留作 UI 显示(由 slug 派生)。
    #[serde(default)]
    pub role_slug: String,
    /// JSON 数组:本 worker 产出的 typed output-kinds(P0-A)。空 = ["done"]。
    #[serde(default)]
    pub produces_json: String,
    /// JSON 数组:{from_role, kind} typed 上游依赖(P0-A)。解析后的 minted key
    /// 落在 `depends_on_json`。
    #[serde(default)]
    pub consumes_json: String,
}

/// 同 NewWorker,加上 spawned_at(已经在 NewWorker 里)— 用一个 struct
/// 简化,后续如果加可选字段再分。
pub type WorkerRecord = NewWorker;

/// Full spell_runs row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpellRunRecord {
    pub id: String,
    pub workspace_id: String,
    pub spell_name: String,
    pub task: String,
    #[serde(default)]
    pub caller_agent_id: Option<String>,
    pub started_at: i64,
}

/// New message (insert payload for [`crate::Store::insert_message`]).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewMessage {
    pub from_agent: String,
    pub to_agent: String,
    pub kind: String,
    pub body: String,
    pub sent_at: i64,
    /// Optional parent message id to thread this reply to.
    #[serde(default)]
    pub in_reply_to: Option<i64>,
    /// Optional structured metadata for system-generated messages (Slack
    /// `event_payload`-style). e.g. `{"subtype":"wake","reason":"blackboard",
    /// "key":"<bb key>"}` or `{"subtype":"completion","signal":"reviewer.done"}`.
    /// The UI renders/filters from this instead of regex-parsing the prose body.
    /// `None` for agent free-text messages (UI falls back to heuristics there).
    #[serde(default)]
    pub meta: Option<serde_json::Value>,
}

/// Full message row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageRecord {
    pub id: i64,
    pub from_agent: String,
    pub to_agent: String,
    pub kind: String,
    pub body: String,
    pub sent_at: i64,
    pub delivered_at: Option<i64>,
    pub read_at: Option<i64>,
    #[serde(default)]
    pub in_reply_to: Option<i64>,
    #[serde(default)]
    pub thread_id: Option<String>,
    /// Structured metadata for system messages (see [`NewMessage::meta`]).
    #[serde(default)]
    pub meta: Option<serde_json::Value>,
}

/// Filter options for [`crate::Store::list_messages`].
///
/// `to_agent=None` means "any recipient". `limit` is required to bound result
/// size — callers should pick a sensible default (e.g. 200).
#[derive(Debug, Clone, Default)]
pub struct ListMessagesOpts {
    pub to_agent: Option<String>,
    pub from_agent: Option<String>,
    pub only_undelivered: bool,
    pub limit: i64,
}

/// New blackboard op (insert payload for [`crate::Store::insert_blackboard_op`]).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewBlackboardOp {
    /// Optional — `None` means the op came from an external editor (watcher
    /// path), not from an agent's `write_blackboard` call.
    pub agent_id: Option<String>,
    /// "write" | "external" — open string so callers can extend later.
    pub op: String,
    /// Path relative to the blackboard root, e.g. "tasks.md".
    pub path: String,
    pub content: String,
    pub sha256: String,
    pub at: i64,
}

/// Full blackboard op row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlackboardOpRecord {
    pub id: i64,
    pub agent_id: Option<String>,
    pub op: String,
    pub path: String,
    pub content: String,
    pub sha256: String,
    pub at: i64,
}

/// New PTY recording (insert payload for [`crate::Store::record_recording_start`]).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewRecording {
    pub id: String,
    pub agent_id: String,
    /// Absolute path to the .cast file on disk.
    pub path: String,
    pub started_at: i64,
    pub cols: i64,
    pub rows: i64,
}

/// Full pty_recordings row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecordingRecord {
    pub id: String,
    pub agent_id: String,
    pub path: String,
    pub started_at: i64,
    pub finalized_at: Option<i64>,
    pub duration_ms: Option<i64>,
    pub cols: i64,
    pub rows: i64,
    pub last_seq: Option<i64>,
}

/// Token usage aggregated by model (`agent_usage` GROUP BY model). Cost is NOT
/// here — the server applies its pricing table at query time.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageByModel {
    pub model: Option<String>,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub cache_read_tokens: i64,
    pub cache_write_tokens: i64,
    pub events: i64,
    /// Peak single-request context occupancy = MAX(input + cache_read +
    /// cache_write) over events — i.e. how full the context window got, vs the
    /// model's static cap. 0 when there are no events.
    pub context_peak: i64,
}

/// Token usage aggregated by calendar day (UTC `YYYY-MM-DD`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageByDay {
    pub day: String,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub cache_read_tokens: i64,
    pub cache_write_tokens: i64,
}

/// Token usage aggregated by agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageByAgent {
    pub agent_id: String,
    pub role: Option<String>,
    pub workspace_id: Option<String>,
    pub thread_id: Option<String>,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub cache_read_tokens: i64,
    pub cache_write_tokens: i64,
    pub events: i64,
}

/// A user-defined scheduled prompt (`cron_jobs` row).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CronJobRecord {
    pub id: String,
    pub workspace_id: String,
    pub name: String,
    pub cron_expr: String,
    pub prompt: String,
    pub enabled: bool,
    pub created_at: i64,
    pub last_run_at: Option<i64>,
}

/// A first-class goal attached to a workspace and optionally one direction
/// (`thread_id = NULL` means the workspace's main/default direction).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalRecord {
    pub id: String,
    pub workspace_id: String,
    pub thread_id: Option<String>,
    pub objective: String,
    /// JSON array of strings, kept as text so the storage layer stays schema-
    /// light while the API can still present structured criteria.
    pub success_criteria: String,
    pub status: String,
    pub budget_tokens: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
    pub completed_at: Option<i64>,
}

#[derive(Debug, Clone)]
pub struct NewGoal {
    pub id: String,
    pub workspace_id: String,
    pub thread_id: Option<String>,
    pub objective: String,
    pub success_criteria: String,
    pub status: String,
    pub budget_tokens: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
    pub completed_at: Option<i64>,
}

/// One observed fact attached to a goal. This is intentionally broad enough to
/// cover human notes, blackboard artifacts, verification commands, and future
/// automated checks while keeping the goal table itself small.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalEvidenceRecord {
    pub id: String,
    pub goal_id: String,
    pub kind: String,
    pub summary: String,
    pub source_agent_id: Option<String>,
    pub blackboard_path: Option<String>,
    pub command: Option<String>,
    pub created_at: i64,
}

#[derive(Debug, Clone)]
pub struct NewGoalEvidence {
    pub id: String,
    pub goal_id: String,
    pub kind: String,
    pub summary: String,
    pub source_agent_id: Option<String>,
    pub blackboard_path: Option<String>,
    pub command: Option<String>,
    pub created_at: i64,
}

/// A worker viewed as a Kanban task: its identity + the raw lifecycle signals
/// the server needs to derive an effective status (alive/done/blocked/…), plus
/// the human `task_status` override. The derivation itself lives in the server
/// (`routes::tasks`) so it can be unit-tested without a DB.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskRecord {
    pub agent_id: String,
    pub parent_agent_id: String,
    pub role_label: String,
    pub role_slug: Option<String>,
    pub handoff_signal: Option<String>,
    /// Human override set from the board (NULL = derive from lifecycle).
    pub task_status: Option<String>,
    pub spawned_at: i64,
    pub killed_at: Option<i64>,
    pub shim_exit_code: Option<i64>,
    pub last_activity_at: Option<i64>,
    pub workspace_id: Option<String>,
    pub thread_id: Option<String>,
    /// True if the worker's `handoff_signal` key exists on the blackboard.
    pub handoff_done: bool,
    /// True if `<handoff_signal>.error` exists (producer-died fallback fired).
    pub error_present: bool,
}
